#!/bin/bash

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

# Regex for your format:
# [#<number>] | message | name/name
pattern='^\[#([0-9]+)\] \| .+ \| .+\/.+$'

if [[ ! $commit_msg =~ $pattern ]]; then
  echo "❌ Invalid commit message format"
  echo "Expected format:"
  echo "[#<story number>] | <commit message> | <author>/<pair>"
  echo "Example:"
  echo "[#21] | Creates lobby | Rahul/Sagnik"
  exit 1
fi

exit 0